# Generated by Django 3.0.4 on 2020-03-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
